
const weather = [
    {name: 'Sunny', icon: 'weather-sunny'},
    {name: 'Clear', icon: 'weather-night'},
    {name: 'Cloudy', icon: 'weather-cloudy', iconNight: 'weather-cloudy' },
    {name: 'Snowy', icon: 'weather-snowy' , iconNight: 'weather-snowy' },
    {name: 'Mist', icon: 'weather-cloudy', iconNight: 'weather-cloudy' },
    {name: 'Overcast', icon: 'weather-partly-cloudy', iconNight: 'weather-night-partly-cloudy' },
    {name: 'Partly cloudy', icon: 'weather-partly-cloudy', iconNight: 'weather-night-partly-cloudy' },
    {name: 'Patchy rain possible', icon: 'weather-partly-rainy', iconNight: 'weather-night-rainy' },
    {name: 'Thundery outbreaks possible', icon: 'weather-lightning', iconNight: 'weather-lightning' },
    {name: 'Patchy light drizzle', icon: 'weather-partly-rainy', iconNight: 'weather-night-rainy' },
    {name: 'Fog', icon: 'weather-cloudy', iconNight: 'weather-cloudy' },
    {name: 'Moderate rain at times', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Moderate rain', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Heavy rain at times', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Heavy rain', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Light freezing rain', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Moderate or heavy freezing rain', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Light rain shower', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Moderate or heavy rain shower', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Torrential rain shower', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Light rain', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Patchy light rain', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Torrential rain shower', icon: 'weather-pouring', iconNight: 'weather-pouring' },
    {name: 'Patchy sleet possible', icon: 'weather-partly-cloudy', iconNight: 'weather-night-partly-cloudy' },
    {name: 'Light sleet', icon: 'weather-snowy-rainy', iconNight: 'weather-snowy-rainy' },
    {name: 'Light sleet showers', icon: 'weather-snowy-rainy', iconNight: 'weather-snowy-rainy' },
    {name: 'Moderate or heavy sleet', icon: 'weather-snowy-rainy', iconNight: 'weather-snowy-rainy' },
    {name: 'Patchy light snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Light snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Patchy moderate snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Moderate snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Patchy heavy snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Heavy snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Patchy snow possible', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Moderate or heavy snow showers', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Ice pellets', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Light showers of ice pellets', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Blowing snow', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Moderate or heavy showers of ice pellets', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Blizzard', icon: 'weather-snowy', iconNight: 'weather-snowy' },
    {name: 'Light drizzle', icon: 'weather-partly-rainy', iconNight: 'weather-partly-rainy' },
    {name: 'Patchy freezing drizzle possible', icon: 'weather-partly-rainy', iconNight: 'weather-partly-rainy' },
    {name: 'Freezing drizzle', icon: 'weather-partly-rainy', iconNight: 'weather-partly-rainy' },
    {name: 'Light drizzle', icon: 'weather-partly-rainy', iconNight: 'weather-partly-rainy' },
    {name: 'Heavy Freezing drizzle', icon: 'weather-partly-cloudy', iconNight: 'weather-night-partly-cloudy' },
    {name: 'Patchy light rain with thunder', icon: 'weather-lightning-rainy', iconNight: 'weather-lightning-rainy' },
    {name: 'Moderate or heavy rain with thunder', icon: 'weather-lightning-rainy', iconNight: 'weather-lightning-rainy' },
    {name: 'Patchy light snow with thunder', icon: 'weather-lightning-rainy', iconNight: 'weather-lightning-rainy' },
    {name: 'Moderate or heavy snow with thunder', icon: 'weather-lightning-rainy', iconNight: 'weather-lightning-rainy' },
    {name: 'Freezing fog', icon: 'weather-cloudy', iconNight: 'weather-cloudy' },
    
  
  ];

export default weather;